local job=vim.fn.jobstart({'nvim','--embed','--headless','-u','NONE','-i','NONE'},{rpc=true})
local function call(method,...) return vim.rpcrequest(job,method,...) end
local function lua(code) local ok,r=pcall(call,'nvim_exec_lua',code,{}); if not ok then error(vim.inspect(r).." CODE: "..code) end; return r end
local function input(s) call('nvim_input',s);vim.wait(180) end
-- No external UI required for RPC-driven input
lua("vim.opt.rtp:prepend("..vim.inspect(vim.fn.getcwd())..");vim.g.mapleader=' ';require('wordvim.help').setup();vim.bo.filetype='wordvim-table'")
vim.rpcnotify(job,'nvim_exec_lua',"vim.ui.input({prompt='Cell: ',default='draft text'},function(v) vim.g.answer=v end)",{})
vim.wait(150)
input('<F1>')
assert(lua('return #vim.api.nvim_list_wins()')==3,'help not opened')
assert(lua('for _,b in ipairs(vim.api.nvim_list_bufs()) do if vim.bo[b].filetype=="wordvimhelp" then return table.concat(vim.api.nvim_buf_get_lines(b,0,-1,false),string.char(10)) end end'):find('DOCX TABLE',1,true),'context')
input('<Tab><CR>')
assert(lua('for _,w in ipairs(vim.api.nvim_list_wins()) do local b=vim.api.nvim_win_get_buf(w); if vim.bo[b].filetype=="wordvimhelp" then return vim.api.nvim_win_get_cursor(w)[1] end end')>8,'prompt contents link')
input('<BS>')
input('<F1>')
assert(lua('return vim.fn.getcmdline()')=='draft text','lost commandline draft')
input('<CR>')
assert(lua('return vim.g.answer')=='draft text','lost cell answer')
print('PASS embedded UI: F1 inside cell prompt restores original draft')
lua("vim.bo.filetype='java';vim.api.nvim_buf_set_lines(0,0,-1,false,{'draft'})")
input('A<F1>')
assert(lua('return vim.bo.filetype')=='wordvimhelp','insert help')
input('<F1>')
assert(lua("return vim.fn.mode()")=='i','restore insert mode')
input('X<Esc>')
assert(lua('return vim.api.nvim_get_current_line()')=='draftX','insert position')
print('PASS embedded UI: Insert mode and cursor restored')
lua("vim.b.wordvim_docx=true; require('wordvim.tables').open(2,2)")
local grid=lua('return vim.api.nvim_buf_get_lines(0,0,-1,false)')
local gridwin=lua('return vim.api.nvim_get_current_win()')
input('<F1>')
assert(lua('return vim.api.nvim_get_current_line()'):find('DOCX TABLE',1,true),'actual table context')
input('q')
assert(lua('return vim.api.nvim_get_current_win()')==gridwin,'table return')
assert(vim.deep_equal(grid,lua('return vim.api.nvim_buf_get_lines(0,0,-1,false)')),'table data changed')
input('Q')
print('PASS actual table editor: shared F1 and unchanged grid on return')
lua("vim.cmd('enew!');vim.fn.termopen({'powershell','-NoProfile'});vim.cmd('startinsert')")
vim.wait(300)
input('<F1>')
assert(lua('return vim.bo.filetype')=='wordvimhelp','terminal help')
input('<F1>')
assert(lua('return vim.fn.mode()')=='t','terminal mode restoration')
print('PASS terminal F1 and terminal input mode restoration')
vim.fn.jobstop(job)
vim.cmd('qa!')



