vim.opt.rtp:prepend(vim.fn.getcwd())
local m=require('wordvim.images')
vim.api.nvim_buf_set_lines(0,0,-1,false,{'![Image](image.png){width=50%}'})
local path=vim.fn.tempname()..'.docx'
vim.fn.writefile(vim.fn.readfile('tests629/50p.docx','b'),path,'b')
assert(m.apply_to_docx(path,0),'write percent metadata')
local lines=m.restore_percent_widths({'![Image](image.png){width="3in"}'},path)
assert(lines[1]=='![Image](image.png){width=50%}',vim.inspect(lines))
assert(m.apply_to_docx(path,0),'repeat metadata update')
local again=m.restore_percent_widths(lines,path)
assert(vim.deep_equal(again,lines),'idempotence')
print('PASS actual DOCX ZIP percentage metadata save/restore and repeated update')
vim.fn.delete(path)
vim.cmd('qa!')
