local M = {}
function M.docx()
  return {
    "",
    "LISTS AND PASTE",
    "---------------",
    "Numbered lists update after Normal edits / leaving Insert mode.",
    ":WordListRenumber    Renumber immediately",
    ":WordListMoveUp / :WordListMoveDown  Move item and its subitems",
    "Alt+Up / Alt+Down    Move list item (Normal mode)",
    ":WordTableCopy / :WordTablePaste    Copy table including styles; :WordTableCut moves it",
    "Space wp / :WordPaste  Paste external HTML, picture or text",
    ":WordInsertFile PATH  Insert DOCX/HTML/image file at cursor",
    "Clipboard: Windows HTML/image; Linux wl-paste/xclip; proot text fallback.",
    "Use file insertion when rich clipboard data is unavailable.",
    "External fonts, borders and shading may be simplified; spans are imported.",
    "Table editor: Enter sets any style number; Space w r toggles styles.",
    "Edit table text in the document buffer, not in the table editor.",
    "",
    "GENERAL",
    "-------",
    "F1 / Space w h       Open / close global Help",
    ":WordHelp            Open / close this Help window",
    ":w                   Save DOCX",
    "q / Esc              Close Help window",
    "",
    "PARAGRAPHS",
    "----------",
    "Enter                New Word paragraph",
    "Shift+Enter / Ctrl+g Enter   Line break in same paragraph (Insert)",
    ":WordKeyCheck        Diagnose terminal Shift+Enter input",
    ":WordTerminalSetup   Fix Windows Terminal Shift+Enter; backs up settings",
    "o                    New paragraph below",
    "O                    New paragraph above",
    "dd                   Delete paragraph with Word Vim metadata",
    "",
    "FORMATTING  (Visual mode)",
    "-------------------------",
    "Space b              Bold",
    "Space i              Italic",
    "Space u              Underline (++text++ in editor)",
    "Space s              Strikeout",
    "",
    "HEADINGS",
    "--------",
    "Space 1              Heading 1",
    "Space 2              Heading 2",
    "Space 3              Heading 3",
    "Space 4              Heading 4",
    "Space 5              Heading 5",
    "Space 6              Heading 6",
    "",
    "LISTS",
    "-----",
    "Space l b            Bullet list / toggle",
    "Space l n            Numbered list / toggle",
    "Visual + Space l b   Bullet list for selection",
    "Visual + Space l n   Numbered list for selection",
    "Enter                Continue same list/level at end of item",
    "Enter on empty item  Exit list -> Normal paragraph",
    "Space l x            Exit/cancel current list item",
    "Tab                  Increase list level when on list item",
    "Shift+Tab            Decrease list level when on list item",
    "",
    "WORD TABS / PARAGRAPH INDENT",
    "----------------------------",
    "Insert: Tab          Insert genuine Word TAB at cursor",
    "Insert: Shift+Tab    Remove preceding / leading Word TAB",
    "Insert: Backspace    At column 0: remove hidden leading Word TAB",
    "Normal: Tab          Increase paragraph indent",
    "Normal: Shift+Tab    Decrease paragraph indent",
    "",
    "STYLES",
    "------",
    "Space w s            Toggle both Style panels",
    "Space w l            Toggle left style gutter",
    "Space w r            Toggle right style list",
    "Style list: Enter/e  Edit selected style",
    "Style gutter: Enter  Edit style number",
    "Style editor: Enter on Panel color   Choose application panel color",
    "Style editor: Ctrl+s Save style settings and panel color",
    "Style editor: q/Esc  Close editor",
    ":WordStyle           Show current paragraph style",
    ":WordStyles          Choose/apply paragraph style",
    ":WordStyleApply ...  Apply style by name",
    ":WordStyleEdit ...   Edit style by name",
    ":WordStyleNew        Create a new style",
    ":WordStyleWidth 32   Set right panel width",
    ":WordStyleGutterWidth 4  Set left gutter width",
    "",
    "PAGES",
    "-----",
    "Space p b            Insert page break before paragraph",
    "Space p d            Delete page break before paragraph",
    "Space p s            Page Setup",
    "Page Setup: Enter/e  Edit selected setting",
    "Page Setup: Ctrl+s   Save and close",
    "Page Setup: q/Esc    Cancel",
    ":WordPageRecalculate Recalculate virtual page boundaries",
    "",
    "TABLE OF CONTENTS",
    "-----------------",
    "Space t c            Insert Table of Contents",
    "Space t d            Delete Table of Contents",
    "Space t o            Open / close Contents window",
    "Contents: Enter/e    Jump to heading",
    "Contents: q/Esc      Close Contents window",
    ":WordTOCRefresh      Refresh Table of Contents",
    "",
    "TABLES",
    "------",
    ":WordTable           Create/edit table in floating editor",
    ":WordTable 5 4       Create a 5 x 4 table",
    "  Enter / 1-9 / . cell style | M, move, M merge | U split",
    "  S cell style | B cell borders | L table borders",
    "  H header rows | A/D row | I/X column | R delete | W save | Q cancel",
    "",
    "IMAGES",
    "------",
    "Space i i            Open Neo-tree image picker",
    "Image picker: Enter  Open folder / insert selected image",
    "Image picker: q/Esc  Cancel image picker",
    ":WordImageWidth 8cm  Set image width",
    ":WordImageScale 50   Set image width to 50%",
    ":WordImageResize 125 Resize current width to 125%",
    ":WordImageRotate 90  Rotate 90 / 180 / 270 degrees",
    ":WordImageReset      Reset natural image size",
    "",
    "CAPTIONS / CROSS-REFERENCES",
    "---------------------------",
    "Space c f            Insert Figure caption",
    "Space c t            Insert Table caption",
    "Space r f            Insert Figure reference",
    "Space r t            Insert Table reference",
    "Reference picker: Enter/e  Select item",
    "Reference picker: q/Esc    Cancel",
    "",
    "LANGUAGE",
    "--------",
    "Space l e            Insert language: English",
    "Space l r            Insert language: Russian",
    "Space l o            Insert language: Romanian",
    ":WordLanguage en     DOCX proofing language: English",
    ":WordLanguage ru     DOCX proofing language: Russian",
    ":WordLanguage ro     DOCX proofing language: Romanian",
    "",
    "WINDOW NAVIGATION  (standard Neovim)",
    "------------------------------------",
    "Ctrl+w h             Window left",
    "Ctrl+w j             Window down",
    "Ctrl+w k             Window up",
    "Ctrl+w l             Window right",
    "",
  }
end

return M
