-- ============================================================
-- lua/wordvim/images.lua
--
-- Basic DOCX image support through Pandoc Markdown.
--
-- Examples:
--
-- ![Caption](<C:/path/image.png>){width=8cm}
--
-- Word Vim changes width only for normal resizing, therefore
-- the image aspect ratio is preserved automatically.
--
-- Rotation is implemented by creating a rotated temporary copy
-- of the image. The original source image is never modified.
-- Supported rotation angles: 90, 180, 270 degrees.
-- ============================================================

local M = {}

local function normalize_path(path)
  path = vim.trim(path or "")
  path = path:gsub("\\", "/")
  return path
end

local function ps_escape(value)
  return tostring(value or ""):gsub("'", "''")
end

local function run_powershell(script)
  local output = vim.fn.system({
    "powershell",
    "-NoProfile",
    "-ExecutionPolicy",
    "Bypass",
    "-Command",
    script,
  })

  return vim.v.shell_error == 0, output
end

local function escape_alt(text)
  text = tostring(text or "")
  text = text:gsub("\\", "\\\\")
  text = text:gsub("%[", "\\[")
  text = text:gsub("%]", "\\]")
  return text
end

local function current_line()
  return vim.fn.getline(".")
end

local function current_line_is_image()
  return current_line():match("!%[.-%]%(") ~= nil
end

local function extract_image_path(line)
  -- Prefer the angle-bracket form generated by Word Vim:
  -- ![...](<C:/path/image.png>)
  local path = line:match("!%[.-%]%(<(.-)>%)")

  if path then
    return path
  end

  -- Fallback for simple Markdown image paths without spaces.
  return line:match("!%[.-%]%(([^%)]+)%)")
end

local function replace_image_path(line, new_path)
  local replaced, count = line:gsub(
    "(!%[.-%]%()%<.-%>(%))",
    "%1<" .. new_path .. ">%2",
    1
  )

  if count > 0 then
    return replaced
  end

  -- Fallback form.
  replaced, count = line:gsub(
    "(!%[.-%]%()([^%)]+)(%))",
    "%1<" .. new_path .. ">%3",
    1
  )

  return replaced
end

local function ensure_image_line()
  if not current_line_is_image() then
    vim.notify(
      "Word Vim: put the cursor on an image line first",
      vim.log.levels.WARN
    )
    return false
  end

  return true
end

local function set_image_width(width)
  width = vim.trim(width or "")

  if width == "" then
    vim.notify(
      "Word Vim: width is empty. Example: :WordImageWidth 8cm",
      vim.log.levels.WARN
    )
    return
  end

  if not ensure_image_line() then
    return
  end

  local line = current_line()

  if line:match("{[^}]*}") then
    if line:match("width%s*=") then
      line = line:gsub(
        'width%s*=%s*[^%s}]+',
        "width=" .. width,
        1
      )
    else
      line = line:gsub(
        "{([^}]*)}",
        function(attrs)
          attrs = vim.trim(attrs)

          if attrs == "" then
            return "{width=" .. width .. "}"
          end

          return "{" .. attrs .. " width=" .. width .. "}"
        end,
        1
      )
    end
  else
    line = line .. "{width=" .. width .. "}"
  end

  vim.fn.setline(".", line)

  vim.notify(
    "Word Vim: image width = " .. width .. " (aspect ratio preserved)",
    vim.log.levels.INFO
  )
end

local function get_current_width()
  local line = current_line()
  return line:match('width%s*=%s*([^%s}]+)')
end

local function parse_dimension(value)
  if not value then
    return nil
  end

  local number, unit = value:match("^([%d%.]+)([%a%%]+)$")

  if not number or not unit then
    return nil
  end

  return tonumber(number), unit
end

local function scale_current_width(factor_percent)
  if not ensure_image_line() then
    return
  end

  local factor = tonumber(factor_percent)

  if not factor or factor <= 0 then
    vim.notify(
      "Word Vim: example: :WordImageResize 125",
      vim.log.levels.WARN
    )
    return
  end

  local width = get_current_width()

  if not width then
    vim.notify(
      "Word Vim: this image has no explicit width yet.\n"
        .. "Set one first, for example :WordImageWidth 8cm",
      vim.log.levels.WARN
    )
    return
  end

  local number, unit = parse_dimension(width)

  if not number then
    vim.notify(
      "Word Vim: unsupported width format: " .. width,
      vim.log.levels.WARN
    )
    return
  end

  local new_value = number * factor / 100

  local formatted
  if math.abs(new_value - math.floor(new_value)) < 0.000001 then
    formatted = tostring(math.floor(new_value))
  else
    formatted = string.format("%.2f", new_value):gsub("0+$", ""):gsub("%.$", "")
  end

  set_image_width(formatted .. unit)
end

local function reset_image_size()
  if not ensure_image_line() then
    return
  end

  local line = current_line()

  line = line:gsub(
    "{([^}]*)}",
    function(attrs)
      attrs = attrs:gsub('width%s*=%s*[^%s}]+', "")
      attrs = attrs:gsub('height%s*=%s*[^%s}]+', "")
      attrs = attrs:gsub("%s+", " ")
      attrs = vim.trim(attrs)

      if attrs == "" then
        return ""
      end

      return "{" .. attrs .. "}"
    end,
    1
  )

  vim.fn.setline(".", line)

  vim.notify(
    "Word Vim: explicit image size removed",
    vim.log.levels.INFO
  )
end

local function get_media_dir()
  local buf = vim.api.nvim_get_current_buf()
  local media_dir = vim.b[buf].wordvim_media_dir

  if media_dir and media_dir ~= "" then
    return media_dir
  end

  media_dir = vim.fn.tempname() .. "_wordvim_media"
  vim.fn.mkdir(media_dir, "p")
  vim.b[buf].wordvim_media_dir = media_dir
  return media_dir
end

local function rotate_image(angle)
  if not ensure_image_line() then
    return
  end

  angle = tonumber(angle)

  if angle ~= 90 and angle ~= 180 and angle ~= 270 then
    vim.notify(
      "Word Vim: supported rotation angles are 90, 180, and 270",
      vim.log.levels.WARN
    )
    return
  end

  local line = current_line()
  local source = extract_image_path(line)

  if not source or source == "" then
    vim.notify(
      "Word Vim: could not determine the image path",
      vim.log.levels.ERROR
    )
    return
  end

  source = normalize_path(source)

  if vim.fn.filereadable(source) ~= 1 then
    vim.notify(
      "Word Vim: image file not found:\n" .. source,
      vim.log.levels.ERROR
    )
    return
  end

  local media_dir = get_media_dir()

  local basename = vim.fn.fnamemodify(source, ":t:r")
  local ext = vim.fn.fnamemodify(source, ":e")

  if ext == "" then
    ext = "png"
  end

  local target =
    normalize_path(media_dir)
    .. "/"
    .. basename
    .. "_rot"
    .. tostring(angle)
    .. "_"
    .. tostring(vim.loop.hrtime())
    .. "."
    .. ext

  local rotate_flip = ({
    [90] = "Rotate90FlipNone",
    [180] = "Rotate180FlipNone",
    [270] = "Rotate270FlipNone",
  })[angle]

  local script = string.format([[
Add-Type -AssemblyName System.Drawing

$source = '%s'
$target = '%s'

$image = $null
$clone = $null

try {
    $image = [System.Drawing.Image]::FromFile($source)
    $clone = New-Object System.Drawing.Bitmap($image)

    $clone.RotateFlip(
      [System.Drawing.RotateFlipType]::%s
    )

    $clone.Save($target)
}
finally {
    if ($null -ne $clone) {
        $clone.Dispose()
    }

    if ($null -ne $image) {
        $image.Dispose()
    }
}
]],
    ps_escape(source),
    ps_escape(target),
    rotate_flip
  )

  local ok, output = run_powershell(script)

  if not ok or vim.fn.filereadable(target) ~= 1 then
    vim.notify(
      "Word Vim: image rotation failed:\n" .. output,
      vim.log.levels.ERROR
    )
    return
  end

  line = replace_image_path(line, target)
  vim.fn.setline(".", line)

  vim.notify(
    "Word Vim: image rotated " .. angle .. " degrees",
    vim.log.levels.INFO
  )
end

local function insert_image_path(path)
  path = normalize_path(path)

  if path == "" then
    return
  end

  path = path:gsub('^"(.*)"$', "%1")
  path = path:gsub("^'(.*)'$", "%1")

  if vim.fn.filereadable(path) ~= 1 then
    vim.notify(
      "Word Vim: image file not found:\n" .. path,
      vim.log.levels.ERROR
    )
    return
  end

  local ext = vim.fn.fnamemodify(path, ":e"):lower()
  local allowed = {
    png = true,
    jpg = true,
    jpeg = true,
    webp = true,
    gif = true,
    bmp = true,
    tif = true,
    tiff = true,
    svg = true,
  }

  if not allowed[ext] then
    vim.notify(
      "Word Vim: selected file is not a supported image: " .. path,
      vim.log.levels.WARN
    )
    return
  end

  local caption = vim.fn.input("Caption/alt text (optional): ")
  local width = vim.fn.input(
    "Width (blank = natural, examples: 8cm, 120mm, 50%): "
  )

  local line =
    "!["
    .. escape_alt(caption)
    .. "](<"
    .. path
    .. ">)"

  width = vim.trim(width)

  if width ~= "" then
    line = line .. "{width=" .. width .. "}"
  end

  vim.api.nvim_put(
    { line },
    "l",
    true,
    true
  )

  vim.notify(
    "Word Vim: image inserted",
    vim.log.levels.INFO
  )
end

local function insert_image(opts)
  local path = opts.args

  if path == "" then
    path = vim.fn.input("Image file: ")
  end

  insert_image_path(path)
end

local function telescope_image_picker()
  if not vim.b.wordvim_docx then
    vim.notify("Word Vim: open a DOCX document first", vim.log.levels.WARN)
    return
  end

  local ok_builtin, builtin = pcall(require, "telescope.builtin")
  local ok_actions, actions = pcall(require, "telescope.actions")
  local ok_state, action_state = pcall(require, "telescope.actions.state")

  if not (ok_builtin and ok_actions and ok_state) then
    vim.notify(
      "Word Vim: Telescope is not available. Use :WordImage <path> instead.",
      vim.log.levels.ERROR
    )
    return
  end

  local docx = vim.b.docx_original_file or vim.api.nvim_buf_get_name(0)
  local cwd = vim.fn.fnamemodify(docx, ":p:h")

  builtin.find_files({
    prompt_title = "Word Vim: Select image",
    cwd = cwd,
    hidden = false,
    attach_mappings = function(prompt_bufnr, map)
      local function choose()
        local entry = action_state.get_selected_entry()
        if not entry then
          return
        end

        local selected = entry.path or entry.filename or entry.value
        if not selected or selected == "" then
          return
        end

        if not selected:match("^%a:[/\\]") and selected:sub(1, 1) ~= "/" then
          selected = cwd .. "/" .. selected
        end

        actions.close(prompt_bufnr)
        vim.schedule(function()
          insert_image_path(selected)
        end)
      end

      map("i", "<CR>", choose)
      map("n", "<CR>", choose)
      return true
    end,
  })
end

function M.attach(buf)
  vim.keymap.set("n", "<leader>ii", telescope_image_picker, {
    buffer = buf,
    silent = true,
    desc = "Word Vim: select and insert image with Telescope",
  })
end

function M.setup()
  vim.api.nvim_create_user_command(
    "WordImage",
    insert_image,
    {
      nargs = "?",
      complete = "file",
      desc = "Insert an image into the DOCX document",
    }
  )

  vim.api.nvim_create_user_command(
    "WordImagePicker",
    telescope_image_picker,
    {
      desc = "Select and insert an image with Telescope",
    }
  )

  vim.api.nvim_create_user_command(
    "WordImageWidth",
    function(opts)
      set_image_width(opts.args)
    end,
    {
      nargs = 1,
      desc = "Set image width while preserving aspect ratio",
    }
  )

  -- Set width as a percentage directly.
  -- Example: :WordImageScale 50  -> width=50%
  vim.api.nvim_create_user_command(
    "WordImageScale",
    function(opts)
      local percent = tonumber(opts.args)

      if not percent or percent <= 0 then
        vim.notify(
          "Word Vim: example: :WordImageScale 50",
          vim.log.levels.WARN
        )
        return
      end

      set_image_width(tostring(percent) .. "%")
    end,
    {
      nargs = 1,
      desc = "Set image width as a percentage",
    }
  )

  -- Multiply the CURRENT explicit width proportionally.
  -- Example:
  -- width=8cm + :WordImageResize 125 -> width=10cm
  -- width=8cm + :WordImageResize 50  -> width=4cm
  vim.api.nvim_create_user_command(
    "WordImageResize",
    function(opts)
      scale_current_width(opts.args)
    end,
    {
      nargs = 1,
      desc = "Resize current image proportionally by percent",
    }
  )

  vim.api.nvim_create_user_command(
    "WordImageRotate",
    function(opts)
      rotate_image(opts.args)
    end,
    {
      nargs = 1,
      desc = "Rotate image 90, 180, or 270 degrees",
    }
  )

  vim.api.nvim_create_user_command(
    "WordImageReset",
    reset_image_size,
    {
      desc = "Reset image to its natural size",
    }
  )
end

return M
